Upd
AndreyBukalo/nodejs-homework pull request #5
Opened 2022-11-22 14:19 UTC by AndreyBukalo

Доброго дня! Хочу сдати на перевірку Дз 4.  Перевірив , начеб то все працює. Дякую!

2022-11-22 18:34 UTC, Eastvarga commented on controller/contacts.js
> +  console.log(req.user);
консолей бути не повинно

2022-11-22 18:36 UTC, Eastvarga commented on middlewares/authMiddlware.js
> +  const [tokenType, token] = req.headers["authorization"].split(" ");
що буде коли у хедера не буде поля авторізації?
гадаю спочатку треба перевірити чи є саме поле

2022-11-22 18:37 UTC, Eastvarga commented on routes/api/authRouter.js
> +router.use(authMiddleware);
авторізація робить на логіні та сігнапі, Ви впевнені що Ваш сервер працює?

2022-11-22 18:38 UTC, Eastvarga commented on routes/api/authRouter.js
> +  "/signin",
А який раут по завданню повинен бути? Не відповідність ТЗ, це не критично, але людина не повинна до цього звикати

2022-11-22 18:40 UTC, Eastvarga commented on middlewares/authMiddlware.js
> +    const user = jwt.decode(token, process.env.JWT_SECRET);
Чому декодування а не веріфікація? Ви впевнені що просто декодування достатньо?

2022-11-22 18:41 UTC, Eastvarga commented on middlewares/authMiddlware.js
> +    req.user = user;
Ні не вірно, де перевірка на існування юзера з токена у базі, та існування у нього токена доступу відповідного?

2022-11-22 18:42 UTC, Eastvarga requested changes
Є зауваження

2022-11-22 18:52 UTC, AndreyBukalo commented on middlewares/authMiddlware.js
> +    const user = jwt.decode(token, process.env.JWT_SECRET);
Я вибачаюсь , все як у викладача в лмс відео . Навіщо тоді це є у відео якщо це не правильно ?

2022-11-22 18:53 UTC, AndreyBukalo commented on middlewares/authMiddlware.js
> +    req.user = user;
Точно така ж ситуація , все як робив Кирило .

2022-11-22 18:55 UTC, AndreyBukalo commented on routes/api/authRouter.js
> +router.use(authMiddleware);
Так . Я думав Ви теж це запускаєте...

2022-11-22 18:56 UTC, AndreyBukalo commented on routes/api/authRouter.js
> +  "/signin",
😃 це фейл)

2022-11-22 19:03 UTC, AndreyBukalo commented on middlewares/authMiddlware.js
> +  const [tokenType, token] = req.headers["authorization"].split(" ");
Чесно кажучи , робив все як викладач на відео. Я не можу здогадатись ці всі ньюнси.

2022-11-25 08:35 UTC, AndreyBukalo commented
Вніс правки та корективи

2022-11-26 18:21 UTC, merged